#include "TitleScreen.h"
#include "Colors.h"

TitleScreen::TitleScreen( const string &titleText ) :
    Sprite( RectF( Vector2f( 0, 0 ), sdl->getWindowSize() ) ) {
      
  // The texture for this is generated by sdl
  tex = sdl->makeTextTexture( titleText, White );
}

void TitleScreen::update() {
	
  // Use a random color
  color = SDL_RandomSolidColor();
  SDL_SetTextureColorMod( tex, color.r, color.g, color.b );
}
