#include "TitleScreen.h"

#include "Colors.h"
#include "StdWilUtil.h"
#include "Texture.h"

TitleScreen::TitleScreen( const string &titleText ) :
    Sprite( RectF( Vector2f( 0, 0 ), sdl->getWindowSize() ) ) {
  
  name = makeString( "Title/`%s`/%s", titleText.c_str(), name.c_str() );
  
  // The texture for this is generated by sdl
  shared_ptr<Texture> tex = sdl->makeTextTexture( titleText, White );
  
  addAnimationFrame( tex, White, HUGEF );
  
}

void TitleScreen::update() {
  // Overrides Sprite::update().
  
  // Use a random color
  Animation::Frame &animFrame = animation.getCurrentFrame();
  animFrame.color = SDL_RandomSolidColor();
  SDL_SetTextureColorMod( animFrame.tex->sdlTex, animFrame.color.r, animFrame.color.g, animFrame.color.b );
}
